### ISSUE TITLE
inference don't need Pose Mapper and BG Mapper?

### ISSUE THREAD

**Issue by yja1** [PrototypeNx/DETEX#2]
1. if training 4 myself dog photos, there are final learn 9 new tokens?
2. inference don't need input any photos, don't need CLIP Image Encoder, Pose Mapper and BG Mapper?

**Comment by PrototypeNx** [comment]
1. Yes, there are 9 tokens. A target token [new], 4 pose tokens, and 4 background tokens.
2. If you only use [new] in the prompt, there is no need for any other modules. If you use [b] or [p], the corresponding reference image, CLIP image encoder, and the mapper are needed.
