### ISSUE TITLE
如何生成两张ref图像的定制图片？

### ISSUE THREAD

**Issue by Crist-228** [PrototypeNx/DETEX#3]
论文中例如photo of a <new1> dog with [P1] pose in [B2] background这种需要两张ref图像的生成该怎么办，仓库中的示例以及代码好像没找到相关方法。

**Comment by PrototypeNx** [comment]
您好，感谢关注，抱歉回复有些晚。混合两张示例的无关嵌入仅需要在推理时将prompt相应位置的token替换为想要的嵌入。论文中该部分作为消融实验部分给出，如果想实现可以修改一下推理部分的代码，即src/DETEX_modules.py中CLIPEmbedderWrapper中得forward部分，以及sample.py文件。




473680239
***@***.***
